name: Flyway Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up PostgreSQL
        run: |
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib
          sudo service postgresql start
          psql -U postgres -c "CREATE DATABASE postgres;"
          psql -U postgres -c "ALTER USER postgres PASSWORD 'brinda16';"

      - name: Install Flyway
        run: |
          curl -L "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.3.1/flyway-commandline-9.3.1-linux-x64.tar.gz" | tar xz
          sudo ln -s "$PWD/flyway-9.3.1/flyway" /usr/local/bin/flyway

      - name: Run Flyway Migrations
        run: |
          flyway -url=jdbc:postgresql://localhost:5432/postgres -user=postgres -password=brinda16 migrate

